-- Generated from docs\catalogo_compras_rascunho.md.
-- Run after migrations that create public.shopping_catalog_items.

insert into public.shopping_catalog_items (
  name,
  slug,
  display_name,
  aliases,
  shopping_category,
  shopping_subcategory,
  default_quantity_text,
  default_unit,
  notes,
  is_active,
  is_food,
  ingredient_id,
  sort_order
)
values
  ('Peito de Frango', 'peito-de-frango', 'Peito de Frango', ARRAY[]::text[], 'Proteínas', 'Aves', '1kg', 'kg', null, true, true, null, 1),
  ('Sobrecoxa de Frango', 'sobrecoxa-de-frango', 'Sobrecoxa de Frango', ARRAY[]::text[], 'Proteínas', 'Aves', '1kg', 'kg', null, true, true, null, 2),
  ('Moela de Frango', 'moela-de-frango', 'Moela de Frango', ARRAY[]::text[], 'Proteínas', 'Aves', '1kg', 'kg', null, true, true, null, 3),
  ('Patinho', 'patinho', 'Patinho', ARRAY[]::text[], 'Proteínas', 'Bovinos', '1kg', 'kg', null, true, true, null, 4),
  ('Músculo', 'musculo', 'Músculo', ARRAY[]::text[], 'Proteínas', 'Bovinos', '1kg', 'kg', null, true, true, null, 5),
  ('Coxão Mole', 'coxao-mole', 'Coxão Mole', ARRAY[]::text[], 'Proteínas', 'Bovinos', '1kg', 'kg', null, true, true, null, 6),
  ('Coxão Duro', 'coxao-duro', 'Coxão Duro', ARRAY[]::text[], 'Proteínas', 'Bovinos', '1kg', 'kg', null, true, true, null, 7),
  ('Filé Mignon', 'file-mignon', 'Filé Mignon', ARRAY[]::text[], 'Proteínas', 'Bovinos', '1kg', 'kg', null, true, true, null, 8),
  ('Fígado Bovino', 'figado-bovino', 'Fígado Bovino', ARRAY[]::text[], 'Proteínas', 'Bovinos', '1kg', 'kg', null, true, true, null, 9),
  ('Lagarto', 'lagarto', 'Lagarto', ARRAY[]::text[], 'Proteínas', 'Bovinos', '1kg', 'kg', null, true, true, null, 10),
  ('Filé Mignon Suíno', 'file-mignon-suino', 'Filé Mignon Suíno', ARRAY[]::text[], 'Proteínas', 'Suínos', '1kg', 'kg', null, true, true, null, 11),
  ('Lombo Suíno', 'lombo-suino', 'Lombo Suíno', ARRAY[]::text[], 'Proteínas', 'Suínos', '1kg', 'kg', null, true, true, null, 12),
  ('Filé de Tilápia', 'file-de-tilapia', 'Filé de Tilápia', ARRAY[]::text[], 'Proteínas', 'Peixes', '1kg', 'kg', null, true, true, null, 13),
  ('Filé de Aruanã', 'file-de-aruana', 'Filé de Aruanã', ARRAY[]::text[], 'Proteínas', 'Peixes', '1kg', 'kg', null, true, true, null, 14),
  ('Salmão', 'salmao', 'Salmão', ARRAY[]::text[], 'Proteínas', 'Peixes', '500g', 'g', null, true, true, null, 15),
  ('Sardinha Fresca', 'sardinha-fresca', 'Sardinha Fresca', ARRAY[]::text[], 'Proteínas', 'Peixes', '1kg', 'kg', null, true, true, null, 16),
  ('Sardinha em Lata', 'sardinha-em-lata', 'Sardinha em Lata', ARRAY[]::text[], 'Proteínas', 'Proteínas em Conserva e Ovos', '1 lata', 'lata', null, true, true, null, 17),
  ('Atum em Lata', 'atum-em-lata', 'Atum em Lata', ARRAY[]::text[], 'Proteínas', 'Proteínas em Conserva e Ovos', '1 lata', 'lata', null, true, true, null, 18),
  ('Ovos', 'ovos', 'Ovos', ARRAY[]::text[], 'Proteínas', 'Proteínas em Conserva e Ovos', '30 unidades', 'unidades', null, true, true, null, 19),
  ('Presunto', 'presunto', 'Presunto', ARRAY[]::text[], 'Proteínas', 'Frios', '200g', 'g', null, true, true, null, 20),
  ('Peito de Peru', 'peito-de-peru', 'Peito de Peru', ARRAY[]::text[], 'Proteínas', 'Frios', '200g', 'g', null, true, true, null, 21),
  ('Bacon', 'bacon', 'Bacon', ARRAY[]::text[], 'Proteínas', 'Frios', '200g', 'g', null, true, true, null, 22),
  ('Arroz', 'arroz', 'Arroz', ARRAY[]::text[], 'Carboidratos', 'Carboidratos de Base', '1 pacote', 'pacote', null, true, true, null, 23),
  ('Arroz Integral', 'arroz-integral', 'Arroz Integral', ARRAY[]::text[], 'Carboidratos', 'Carboidratos de Base', '1 pacote', 'pacote', null, true, true, null, 24),
  ('Macarrão', 'macarrao', 'Macarrão', ARRAY[]::text[], 'Carboidratos', 'Carboidratos de Base', '1 pacote', 'pacote', null, true, true, null, 25),
  ('Macarrão Integral', 'macarrao-integral', 'Macarrão Integral', ARRAY[]::text[], 'Carboidratos', 'Carboidratos de Base', '1 pacote', 'pacote', null, true, true, null, 26),
  ('Batata Inglesa', 'batata-inglesa', 'Batata Inglesa', ARRAY[]::text[], 'Carboidratos', 'Carboidratos de Base', '1kg', 'kg', null, true, true, null, 27),
  ('Batata Doce', 'batata-doce', 'Batata Doce', ARRAY[]::text[], 'Carboidratos', 'Carboidratos de Base', '1kg', 'kg', null, true, true, null, 28),
  ('Batata Baroa', 'batata-baroa', 'Batata Baroa', ARRAY[]::text[], 'Carboidratos', 'Carboidratos de Base', '1kg', 'kg', null, true, true, null, 29),
  ('Mandioca', 'mandioca', 'Mandioca', ARRAY['Macaxeira', 'Aipim']::text[], 'Carboidratos', 'Carboidratos de Base', '1kg', 'kg', null, true, true, null, 30),
  ('Inhame', 'inhame', 'Inhame', ARRAY[]::text[], 'Carboidratos', 'Carboidratos de Base', '1kg', 'kg', null, true, true, null, 31),
  ('Farinha de Mandioca', 'farinha-de-mandioca', 'Farinha de Mandioca', ARRAY[]::text[], 'Carboidratos', 'Carboidratos de Base', '1 pacote', 'pacote', null, true, true, null, 32),
  ('Feijão Preto', 'feijao-preto', 'Feijão Preto', ARRAY[]::text[], 'Carboidratos', 'Carboidratos de Base', '1kg', 'kg', null, true, true, null, 33),
  ('Feijão Carioca', 'feijao-carioca', 'Feijão Carioca', ARRAY[]::text[], 'Carboidratos', 'Carboidratos de Base', '1kg', 'kg', null, true, true, null, 34),
  ('Pão de Forma', 'pao-de-forma', 'Pão de Forma', ARRAY[]::text[], 'Carboidratos', 'Carboidratos Práticos', '1 pacote', 'pacote', null, true, true, null, 35),
  ('Torrada', 'torrada', 'Torrada', ARRAY[]::text[], 'Carboidratos', 'Carboidratos Práticos', '1 pacote', 'pacote', null, true, true, null, 36),
  ('Rap10', 'rap10', 'Rap10', ARRAY[]::text[], 'Carboidratos', 'Carboidratos Práticos', '1 pacote', 'pacote', null, true, true, null, 37),
  ('Goma de Tapioca', 'goma-de-tapioca', 'Goma de Tapioca', ARRAY[]::text[], 'Carboidratos', 'Carboidratos Práticos', '1 pacote', 'pacote', null, true, true, null, 38),
  ('Flocão de Milho', 'flocao-de-milho', 'Flocão de Milho', ARRAY[]::text[], 'Carboidratos', 'Carboidratos Práticos', '1 pacote', 'pacote', null, true, true, null, 39),
  ('Milho de Pipoca', 'milho-de-pipoca', 'Milho de Pipoca', ARRAY[]::text[], 'Carboidratos', 'Carboidratos Práticos', '500g', 'g', null, true, true, null, 40),
  ('Aveia em Flocos', 'aveia-em-flocos', 'Aveia em Flocos', ARRAY[]::text[], 'Carboidratos', 'Carboidratos Práticos', '1 pacote', 'pacote', null, true, true, null, 41),
  ('Farinha de Aveia', 'farinha-de-aveia', 'Farinha de Aveia', ARRAY[]::text[], 'Carboidratos', 'Carboidratos Práticos', '1 pacote', 'pacote', null, true, true, null, 42),
  ('Farelo de Aveia', 'farelo-de-aveia', 'Farelo de Aveia', ARRAY[]::text[], 'Carboidratos', 'Carboidratos Práticos', '1 pacote', 'pacote', null, true, true, null, 43),
  ('Granola', 'granola', 'Granola', ARRAY[]::text[], 'Carboidratos', 'Carboidratos Práticos', '1 pacote', 'pacote', null, true, true, null, 44),
  ('Biscoitos de Arroz', 'biscoitos-de-arroz', 'Biscoitos de Arroz', ARRAY[]::text[], 'Carboidratos', 'Carboidratos Práticos', '1 pacote', 'pacote', null, true, true, null, 45),
  ('Açúcar', 'acucar', 'Açúcar', ARRAY[]::text[], 'Carboidratos', 'Doces e Açúcares', '1kg', 'kg', null, true, true, null, 46),
  ('Mel de Abelha', 'mel-de-abelha', 'Mel de Abelha', ARRAY[]::text[], 'Carboidratos', 'Doces e Açúcares', '1 unidade', 'unidade', null, true, true, null, 47),
  ('Sucrilhos', 'sucrilhos', 'Sucrilhos', ARRAY[]::text[], 'Carboidratos', 'Doces e Açúcares', '1 pacote', 'pacote', null, true, true, null, 48),
  ('Farinha Láctea', 'farinha-lactea', 'Farinha Láctea', ARRAY[]::text[], 'Carboidratos', 'Doces e Açúcares', '1 pacote', 'pacote', null, true, true, null, 49),
  ('Neston', 'neston', 'Neston', ARRAY[]::text[], 'Carboidratos', 'Doces e Açúcares', '1 pacote', 'pacote', null, true, true, null, 50),
  ('Doce de Leite', 'doce-de-leite', 'Doce de Leite', ARRAY[]::text[], 'Carboidratos', 'Doces e Açúcares', '1 unidade', 'unidade', null, true, true, null, 51),
  ('Goiabada', 'goiabada', 'Goiabada', ARRAY[]::text[], 'Carboidratos', 'Doces e Açúcares', '1 unidade', 'unidade', null, true, true, null, 52),
  ('Geleia de Frutas', 'geleia-de-frutas', 'Geleia de Frutas', ARRAY[]::text[], 'Carboidratos', 'Doces e Açúcares', '1 unidade', 'unidade', null, true, true, null, 53),
  ('Alface', 'alface', 'Alface', ARRAY[]::text[], 'Vegetais', 'Verduras', '1 unidade', 'unidade', null, true, true, null, 54),
  ('Acelga', 'acelga', 'Acelga', ARRAY[]::text[], 'Vegetais', 'Verduras', '1 unidade', 'unidade', null, true, true, null, 55),
  ('Agrião', 'agriao', 'Agrião', ARRAY[]::text[], 'Vegetais', 'Verduras', '1 maço', 'maço', null, true, true, null, 56),
  ('Brócolis', 'brocolis', 'Brócolis', ARRAY[]::text[], 'Vegetais', 'Verduras', '1 unidade', 'unidade', null, true, true, null, 57),
  ('Cebolinha', 'cebolinha', 'Cebolinha', ARRAY[]::text[], 'Vegetais', 'Verduras', '1 maço', 'maço', null, true, true, null, 58),
  ('Cheiro-Verde', 'cheiro-verde', 'Cheiro-Verde', ARRAY[]::text[], 'Vegetais', 'Verduras', '1 maço', 'maço', null, true, true, null, 59),
  ('Coentro', 'coentro', 'Coentro', ARRAY[]::text[], 'Vegetais', 'Verduras', '1 maço', 'maço', null, true, true, null, 60),
  ('Couve', 'couve', 'Couve', ARRAY[]::text[], 'Vegetais', 'Verduras', '1 maço', 'maço', null, true, true, null, 61),
  ('Couve-flor', 'couve-flor', 'Couve-flor', ARRAY[]::text[], 'Vegetais', 'Verduras', '1 unidade', 'unidade', null, true, true, null, 62),
  ('Espinafre', 'espinafre', 'Espinafre', ARRAY[]::text[], 'Vegetais', 'Verduras', '1 maço', 'maço', null, true, true, null, 63),
  ('Hortelã', 'hortela', 'Hortelã', ARRAY[]::text[], 'Vegetais', 'Verduras', '1 maço', 'maço', null, true, true, null, 64),
  ('Repolho', 'repolho', 'Repolho', ARRAY[]::text[], 'Vegetais', 'Verduras', '1 unidade', 'unidade', null, true, true, null, 65),
  ('Rúcula', 'rucula', 'Rúcula', ARRAY[]::text[], 'Vegetais', 'Verduras', '1 maço', 'maço', null, true, true, null, 66),
  ('Salsão', 'salsao', 'Salsão', ARRAY[]::text[], 'Vegetais', 'Verduras', '1 unidade', 'unidade', null, true, true, null, 67),
  ('Abóbora', 'abobora', 'Abóbora', ARRAY[]::text[], 'Vegetais', 'Legumes', '1kg', 'kg', null, true, true, null, 68),
  ('Abobrinha', 'abobrinha', 'Abobrinha', ARRAY[]::text[], 'Vegetais', 'Legumes', '1kg', 'kg', null, true, true, null, 69),
  ('Alho', 'alho', 'Alho', ARRAY[]::text[], 'Vegetais', 'Legumes', '1 cabeça', 'cabeça', null, true, true, null, 70),
  ('Alho Poró', 'alho-poro', 'Alho Poró', ARRAY[]::text[], 'Vegetais', 'Legumes', '1 unidade', 'unidade', null, true, true, null, 71),
  ('Berinjela', 'berinjela', 'Berinjela', ARRAY[]::text[], 'Vegetais', 'Legumes', '1 unidade', 'unidade', null, true, true, null, 72),
  ('Beterraba', 'beterraba', 'Beterraba', ARRAY[]::text[], 'Vegetais', 'Legumes', '1kg', 'kg', null, true, true, null, 73),
  ('Cebola Branca', 'cebola-branca', 'Cebola Branca', ARRAY[]::text[], 'Vegetais', 'Legumes', '1kg', 'kg', null, true, true, null, 74),
  ('Cebola Roxa', 'cebola-roxa', 'Cebola Roxa', ARRAY[]::text[], 'Vegetais', 'Legumes', '1kg', 'kg', null, true, true, null, 75),
  ('Cenoura', 'cenoura', 'Cenoura', ARRAY[]::text[], 'Vegetais', 'Legumes', '1kg', 'kg', null, true, true, null, 76),
  ('Chuchu', 'chuchu', 'Chuchu', ARRAY[]::text[], 'Vegetais', 'Legumes', '1kg', 'kg', null, true, true, null, 77),
  ('Jiló', 'jilo', 'Jiló', ARRAY[]::text[], 'Vegetais', 'Legumes', '1kg', 'kg', null, true, true, null, 78),
  ('Nabo', 'nabo', 'Nabo', ARRAY[]::text[], 'Vegetais', 'Legumes', '1 unidade', 'unidade', null, true, true, null, 79),
  ('Palmito', 'palmito', 'Palmito', ARRAY[]::text[], 'Vegetais', 'Legumes', '1 unidade', 'unidade', null, true, true, null, 80),
  ('Pepino', 'pepino', 'Pepino', ARRAY[]::text[], 'Vegetais', 'Legumes', '2 unidades', 'unidades', null, true, true, null, 81),
  ('Pimenta', 'pimenta', 'Pimenta', ARRAY[]::text[], 'Vegetais', 'Legumes', '1 unidade', 'unidade', null, true, true, null, 82),
  ('Pimentão', 'pimentao', 'Pimentão', ARRAY[]::text[], 'Vegetais', 'Legumes', '3 unidades', 'unidades', null, true, true, null, 83),
  ('Quiabo', 'quiabo', 'Quiabo', ARRAY[]::text[], 'Vegetais', 'Legumes', '1kg', 'kg', null, true, true, null, 84),
  ('Rabanete', 'rabanete', 'Rabanete', ARRAY[]::text[], 'Vegetais', 'Legumes', '1 maço', 'maço', null, true, true, null, 85),
  ('Tomate', 'tomate', 'Tomate', ARRAY[]::text[], 'Vegetais', 'Legumes', '1kg', 'kg', null, true, true, null, 86),
  ('Tomate Cereja', 'tomate-cereja', 'Tomate Cereja', ARRAY[]::text[], 'Vegetais', 'Legumes', '1 bandeja', 'bandeja', null, true, true, null, 87),
  ('Vagem', 'vagem', 'Vagem', ARRAY[]::text[], 'Vegetais', 'Legumes', '1kg', 'kg', null, true, true, null, 88),
  ('Amendoim', 'amendoim', 'Amendoim', ARRAY[]::text[], 'Vegetais', 'Oleaginosas, Sementes e Fibras', '500g', 'g', null, true, true, null, 89),
  ('Pasta de Amendoim', 'pasta-de-amendoim', 'Pasta de Amendoim', ARRAY[]::text[], 'Vegetais', 'Oleaginosas, Sementes e Fibras', '1 pote', 'pote', null, true, true, null, 90),
  ('Castanha do Pará', 'castanha-do-para', 'Castanha do Pará', ARRAY[]::text[], 'Vegetais', 'Oleaginosas, Sementes e Fibras', '500g', 'g', null, true, true, null, 91),
  ('Castanha de Caju', 'castanha-de-caju', 'Castanha de Caju', ARRAY[]::text[], 'Vegetais', 'Oleaginosas, Sementes e Fibras', '500g', 'g', null, true, true, null, 92),
  ('Nozes', 'nozes', 'Nozes', ARRAY[]::text[], 'Vegetais', 'Oleaginosas, Sementes e Fibras', '500g', 'g', null, true, true, null, 93),
  ('Sementes de Abóbora', 'sementes-de-abobora', 'Sementes de Abóbora', ARRAY[]::text[], 'Vegetais', 'Oleaginosas, Sementes e Fibras', '1 pacote', 'pacote', null, true, true, null, 94),
  ('Sementes de Chia', 'sementes-de-chia', 'Sementes de Chia', ARRAY[]::text[], 'Vegetais', 'Oleaginosas, Sementes e Fibras', '1 pacote', 'pacote', null, true, true, null, 95),
  ('Sementes de Girassol', 'sementes-de-girassol', 'Sementes de Girassol', ARRAY[]::text[], 'Vegetais', 'Oleaginosas, Sementes e Fibras', '1 pacote', 'pacote', null, true, true, null, 96),
  ('Sementes de Gergelim', 'sementes-de-gergelim', 'Sementes de Gergelim', ARRAY[]::text[], 'Vegetais', 'Oleaginosas, Sementes e Fibras', '1 pacote', 'pacote', null, true, true, null, 97),
  ('Sementes de Linhaça', 'sementes-de-linhaca', 'Sementes de Linhaça', ARRAY[]::text[], 'Vegetais', 'Oleaginosas, Sementes e Fibras', '1 pacote', 'pacote', null, true, true, null, 98),
  ('Psyllium', 'psyllium', 'Psyllium', ARRAY[]::text[], 'Vegetais', 'Oleaginosas, Sementes e Fibras', '1 pacote', 'pacote', null, true, true, null, 99),
  ('Abacate', 'abacate', 'Abacate', ARRAY[]::text[], 'Frutas', 'Frutas de Casa', '1 unidade', 'unidade', null, true, true, null, 100),
  ('Abacaxi', 'abacaxi', 'Abacaxi', ARRAY[]::text[], 'Frutas', 'Frutas de Casa', '1 unidade', 'unidade', null, true, true, null, 101),
  ('Açaí', 'acai', 'Açaí', ARRAY[]::text[], 'Frutas', 'Frutas de Casa', '1kg', 'kg', null, true, true, null, 102),
  ('Caju', 'caju', 'Caju', ARRAY[]::text[], 'Frutas', 'Frutas de Casa', '1kg', 'kg', null, true, true, null, 103),
  ('Côco', 'coco', 'Côco', ARRAY[]::text[], 'Frutas', 'Frutas de Casa', '1 unidade', 'unidade', null, true, true, null, 104),
  ('Cupuaçu', 'cupuacu', 'Cupuaçu', ARRAY[]::text[], 'Frutas', 'Frutas de Casa', '1kg', 'kg', null, true, true, null, 105),
  ('Graviola', 'graviola', 'Graviola', ARRAY[]::text[], 'Frutas', 'Frutas de Casa', '1 unidade', 'unidade', null, true, true, null, 106),
  ('Limão Taiti', 'limao-taiti', 'Limão Taiti', ARRAY[]::text[], 'Frutas', 'Frutas de Casa', '1kg', 'kg', null, true, true, null, 107),
  ('Limão Siciliano', 'limao-siciliano', 'Limão Siciliano', ARRAY[]::text[], 'Frutas', 'Frutas de Casa', '1kg', 'kg', null, true, true, null, 108),
  ('Mamão', 'mamao', 'Mamão', ARRAY[]::text[], 'Frutas', 'Frutas de Casa', '1 unidade', 'unidade', null, true, true, null, 109),
  ('Manga', 'manga', 'Manga', ARRAY[]::text[], 'Frutas', 'Frutas de Casa', '1kg', 'kg', null, true, true, null, 110),
  ('Maracujá', 'maracuja', 'Maracujá', ARRAY[]::text[], 'Frutas', 'Frutas de Casa', '1kg', 'kg', null, true, true, null, 111),
  ('Melancia', 'melancia', 'Melancia', ARRAY[]::text[], 'Frutas', 'Frutas de Casa', '1 unidade', 'unidade', null, true, true, null, 112),
  ('Morango', 'morango', 'Morango', ARRAY[]::text[], 'Frutas', 'Frutas de Casa', '1 bandeja', 'bandeja', null, true, true, null, 113),
  ('Pitaya', 'pitaya', 'Pitaya', ARRAY[]::text[], 'Frutas', 'Frutas de Casa', '1 unidade', 'unidade', null, true, true, null, 114),
  ('Taperebá', 'tapereba', 'Taperebá', ARRAY[]::text[], 'Frutas', 'Frutas de Casa', '1kg', 'kg', null, true, true, null, 115),
  ('Ameixa', 'ameixa', 'Ameixa', ARRAY[]::text[], 'Frutas', 'Frutas de Rua', '1kg', 'kg', null, true, true, null, 116),
  ('Banana', 'banana', 'Banana', ARRAY[]::text[], 'Frutas', 'Frutas de Rua', '12 unidades', 'unidades', null, true, true, null, 117),
  ('Caqui', 'caqui', 'Caqui', ARRAY[]::text[], 'Frutas', 'Frutas de Rua', '1kg', 'kg', null, true, true, null, 118),
  ('Damasco', 'damasco', 'Damasco', ARRAY[]::text[], 'Frutas', 'Frutas de Rua', '500g', 'g', null, true, true, null, 119),
  ('Kiwi', 'kiwi', 'Kiwi', ARRAY[]::text[], 'Frutas', 'Frutas de Rua', '1 bandeja', 'bandeja', null, true, true, null, 120),
  ('Laranja', 'laranja', 'Laranja', ARRAY[]::text[], 'Frutas', 'Frutas de Rua', '1kg', 'kg', null, true, true, null, 121),
  ('Maçã', 'maca', 'Maçã', ARRAY[]::text[], 'Frutas', 'Frutas de Rua', '1kg', 'kg', null, true, true, null, 122),
  ('Pêra', 'pera', 'Pêra', ARRAY[]::text[], 'Frutas', 'Frutas de Rua', '1kg', 'kg', null, true, true, null, 123),
  ('Pêssego', 'pessego', 'Pêssego', ARRAY[]::text[], 'Frutas', 'Frutas de Rua', '1kg', 'kg', null, true, true, null, 124),
  ('Tangerina', 'tangerina', 'Tangerina', ARRAY[]::text[], 'Frutas', 'Frutas de Rua', '1kg', 'kg', null, true, true, null, 125),
  ('Uva Rubi', 'uva-rubi', 'Uva Rubi', ARRAY[]::text[], 'Frutas', 'Frutas de Rua', '1 bandeja', 'bandeja', null, true, true, null, 126),
  ('Uva Itália', 'uva-italia', 'Uva Itália', ARRAY[]::text[], 'Frutas', 'Frutas de Rua', '1 bandeja', 'bandeja', null, true, true, null, 127),
  ('Leite Integral', 'leite-integral', 'Leite Integral', ARRAY[]::text[], 'Laticínios', null, '1 litro', 'litro', null, true, true, null, 128),
  ('Leite Semidesnatado', 'leite-semidesnatado', 'Leite Semidesnatado', ARRAY[]::text[], 'Laticínios', null, '1 litro', 'litro', null, true, true, null, 129),
  ('Leite Desnatado', 'leite-desnatado', 'Leite Desnatado', ARRAY[]::text[], 'Laticínios', null, '1 litro', 'litro', null, true, true, null, 130),
  ('Leite em Pó Integral', 'leite-em-po-integral', 'Leite em Pó Integral', ARRAY[]::text[], 'Laticínios', null, '1 lata', 'lata', null, true, true, null, 131),
  ('Leite em Pó Desnatado', 'leite-em-po-desnatado', 'Leite em Pó Desnatado', ARRAY[]::text[], 'Laticínios', null, '1 lata', 'lata', null, true, true, null, 132),
  ('Iogurte Natural Integral', 'iogurte-natural-integral', 'Iogurte Natural Integral', ARRAY[]::text[], 'Laticínios', null, '1 unidade', 'unidade', null, true, true, null, 133),
  ('Iogurte Natural Desnatado', 'iogurte-natural-desnatado', 'Iogurte Natural Desnatado', ARRAY[]::text[], 'Laticínios', null, '1 unidade', 'unidade', null, true, true, null, 134),
  ('Iogurte Molico Triplo Zero', 'iogurte-molico-triplo-zero', 'Iogurte Molico Triplo Zero', ARRAY[]::text[], 'Laticínios', null, '1 unidade', 'unidade', null, true, true, null, 135),
  ('Iogurte Corpus Zero', 'iogurte-corpus-zero', 'Iogurte Corpus Zero', ARRAY[]::text[], 'Laticínios', null, '1 unidade', 'unidade', null, true, true, null, 136),
  ('Iogurte Batavo Pense Zero', 'iogurte-batavo-pense-zero', 'Iogurte Batavo Pense Zero', ARRAY[]::text[], 'Laticínios', null, '1 unidade', 'unidade', null, true, true, null, 137),
  ('Requeijão Light', 'requeijao-light', 'Requeijão Light', ARRAY[]::text[], 'Laticínios', null, '1 unidade', 'unidade', null, true, true, null, 138),
  ('Creme de Ricota Light', 'creme-de-ricota-light', 'Creme de Ricota Light', ARRAY[]::text[], 'Laticínios', null, '1 pote', 'pote', null, true, true, null, 139),
  ('Cream Cheese Light', 'cream-cheese-light', 'Cream Cheese Light', ARRAY[]::text[], 'Laticínios', null, '1 pote', 'pote', null, true, true, null, 140),
  ('Queijo Mussarela', 'queijo-mussarela', 'Queijo Mussarela', ARRAY[]::text[], 'Laticínios', null, '200g', 'g', null, true, true, null, 141),
  ('Queijo Coalho', 'queijo-coalho', 'Queijo Coalho', ARRAY[]::text[], 'Laticínios', null, '200g', 'g', null, true, true, null, 142),
  ('Queijo Minas', 'queijo-minas', 'Queijo Minas', ARRAY[]::text[], 'Laticínios', null, '200g', 'g', null, true, true, null, 143),
  ('Queijo Parmesão', 'queijo-parmesao', 'Queijo Parmesão', ARRAY[]::text[], 'Laticínios', null, '200g', 'g', null, true, true, null, 144),
  ('Manteiga', 'manteiga', 'Manteiga', ARRAY[]::text[], 'Laticínios', null, '1 unidade', 'unidade', null, true, true, null, 145),
  ('Creme de Leite', 'creme-de-leite', 'Creme de Leite', ARRAY[]::text[], 'Laticínios', null, '1 unidade', 'unidade', null, true, true, null, 146),
  ('Brócolis Congelado', 'brocolis-congelado', 'Brócolis Congelado', ARRAY[]::text[], 'Congelados', null, '1 pacote', 'pacote', null, true, true, null, 147),
  ('Couve-flor Congelada', 'couve-flor-congelada', 'Couve-flor Congelada', ARRAY[]::text[], 'Congelados', null, '1 pacote', 'pacote', null, true, true, null, 148),
  ('Ervilhas Congeladas', 'ervilhas-congeladas', 'Ervilhas Congeladas', ARRAY[]::text[], 'Congelados', null, '1 pacote', 'pacote', null, true, true, null, 149),
  ('Vagem Congelada', 'vagem-congelada', 'Vagem Congelada', ARRAY[]::text[], 'Congelados', null, '1 pacote', 'pacote', null, true, true, null, 150),
  ('Mistura Oriental Congelada', 'mistura-oriental-congelada', 'Mistura Oriental Congelada', ARRAY[]::text[], 'Congelados', null, '1 pacote', 'pacote', null, true, true, null, 151),
  ('Morangos Congelados', 'morangos-congelados', 'Morangos Congelados', ARRAY[]::text[], 'Congelados', null, '1 pacote', 'pacote', null, true, true, null, 152),
  ('Açaí Zero', 'acai-zero', 'Açaí Zero', ARRAY[]::text[], 'Congelados', null, '1 unidade', 'unidade', null, true, true, null, 153),
  ('Polpa de Frutas para Suco', 'polpa-de-frutas-para-suco', 'Polpa de Frutas para Suco', ARRAY[]::text[], 'Congelados', null, '1 pacote', 'pacote', null, true, true, null, 154),
  ('Açafrão', 'acafrao', 'Açafrão', ARRAY[]::text[], 'Temperos e Condimentos', 'Temperos Secos', '1 unidade', 'unidade', null, true, true, null, 155),
  ('Alho em Pó', 'alho-em-po', 'Alho em Pó', ARRAY[]::text[], 'Temperos e Condimentos', 'Temperos Secos', '1 unidade', 'unidade', null, true, true, null, 156),
  ('Canela', 'canela', 'Canela', ARRAY[]::text[], 'Temperos e Condimentos', 'Temperos Secos', '1 unidade', 'unidade', null, true, true, null, 157),
  ('Cebola em Pó', 'cebola-em-po', 'Cebola em Pó', ARRAY[]::text[], 'Temperos e Condimentos', 'Temperos Secos', '1 unidade', 'unidade', null, true, true, null, 158),
  ('Cominho', 'cominho', 'Cominho', ARRAY[]::text[], 'Temperos e Condimentos', 'Temperos Secos', '1 unidade', 'unidade', null, true, true, null, 159),
  ('Cravo', 'cravo', 'Cravo', ARRAY[]::text[], 'Temperos e Condimentos', 'Temperos Secos', '1 unidade', 'unidade', null, true, true, null, 160),
  ('Curri', 'curri', 'Curri', ARRAY[]::text[], 'Temperos e Condimentos', 'Temperos Secos', '1 unidade', 'unidade', null, true, true, null, 161),
  ('Gengibre em Pó', 'gengibre-em-po', 'Gengibre em Pó', ARRAY[]::text[], 'Temperos e Condimentos', 'Temperos Secos', '1 unidade', 'unidade', null, true, true, null, 162),
  ('Lemon Pepper', 'lemon-pepper', 'Lemon Pepper', ARRAY[]::text[], 'Temperos e Condimentos', 'Temperos Secos', '1 unidade', 'unidade', null, true, true, null, 163),
  ('Noz Moscada', 'noz-moscada', 'Noz Moscada', ARRAY[]::text[], 'Temperos e Condimentos', 'Temperos Secos', '1 unidade', 'unidade', null, true, true, null, 164),
  ('Páprica Doce', 'paprica-doce', 'Páprica Doce', ARRAY[]::text[], 'Temperos e Condimentos', 'Temperos Secos', '1 unidade', 'unidade', null, true, true, null, 165),
  ('Páprica Defumada', 'paprica-defumada', 'Páprica Defumada', ARRAY[]::text[], 'Temperos e Condimentos', 'Temperos Secos', '1 unidade', 'unidade', null, true, true, null, 166),
  ('Páprica Picante', 'paprica-picante', 'Páprica Picante', ARRAY[]::text[], 'Temperos e Condimentos', 'Temperos Secos', '1 unidade', 'unidade', null, true, true, null, 167),
  ('Pimenta Calabresa', 'pimenta-calabresa', 'Pimenta Calabresa', ARRAY[]::text[], 'Temperos e Condimentos', 'Temperos Secos', '1 unidade', 'unidade', null, true, true, null, 168),
  ('Pimenta do Reino', 'pimenta-do-reino', 'Pimenta do Reino', ARRAY[]::text[], 'Temperos e Condimentos', 'Temperos Secos', '1 unidade', 'unidade', null, true, true, null, 169),
  ('Sal', 'sal', 'Sal', ARRAY[]::text[], 'Temperos e Condimentos', 'Temperos Secos', '1 pacote', 'pacote', null, true, true, null, 170),
  ('Alecrim', 'alecrim', 'Alecrim', ARRAY[]::text[], 'Temperos e Condimentos', 'Ervas Desidratadas', '1 unidade', 'unidade', null, true, true, null, 171),
  ('Chimichurri', 'chimichurri', 'Chimichurri', ARRAY[]::text[], 'Temperos e Condimentos', 'Ervas Desidratadas', '1 unidade', 'unidade', null, true, true, null, 172),
  ('Erva Doce', 'erva-doce', 'Erva Doce', ARRAY[]::text[], 'Temperos e Condimentos', 'Ervas Desidratadas', '1 unidade', 'unidade', null, true, true, null, 173),
  ('Louro', 'louro', 'Louro', ARRAY[]::text[], 'Temperos e Condimentos', 'Ervas Desidratadas', '1 pacote', 'pacote', null, true, true, null, 174),
  ('Orégano', 'oregano', 'Orégano', ARRAY[]::text[], 'Temperos e Condimentos', 'Ervas Desidratadas', '1 unidade', 'unidade', null, true, true, null, 175),
  ('Tomilho', 'tomilho', 'Tomilho', ARRAY[]::text[], 'Temperos e Condimentos', 'Ervas Desidratadas', '1 unidade', 'unidade', null, true, true, null, 176),
  ('Azeite de Oliva Extra Virgem', 'azeite-de-oliva-extra-virgem', 'Azeite de Oliva Extra Virgem', ARRAY[]::text[], 'Temperos e Condimentos', 'Condimentos e Óleos', '1 vidro', 'vidro', null, true, true, null, 177),
  ('Azeite de Oliva Tipo Único', 'azeite-de-oliva-tipo-unico', 'Azeite de Oliva Tipo Único', ARRAY[]::text[], 'Temperos e Condimentos', 'Condimentos e Óleos', '1 vidro', 'vidro', null, true, true, null, 178),
  ('Vinagre de Maçã', 'vinagre-de-maca', 'Vinagre de Maçã', ARRAY[]::text[], 'Temperos e Condimentos', 'Condimentos e Óleos', '1 unidade', 'unidade', null, true, true, null, 179),
  ('Vinagre de Álcool', 'vinagre-de-alcool', 'Vinagre de Álcool', ARRAY[]::text[], 'Temperos e Condimentos', 'Condimentos e Óleos', '1 unidade', 'unidade', null, true, true, null, 180),
  ('Vinagre de Arroz', 'vinagre-de-arroz', 'Vinagre de Arroz', ARRAY[]::text[], 'Temperos e Condimentos', 'Condimentos e Óleos', '1 unidade', 'unidade', null, true, true, null, 181),
  ('Vinagre Balsâmico', 'vinagre-balsamico', 'Vinagre Balsâmico', ARRAY[]::text[], 'Temperos e Condimentos', 'Condimentos e Óleos', '1 unidade', 'unidade', null, true, true, null, 182),
  ('Ketchup', 'ketchup', 'Ketchup', ARRAY[]::text[], 'Temperos e Condimentos', 'Condimentos e Óleos', '1 unidade', 'unidade', null, true, true, null, 183),
  ('Maionese', 'maionese', 'Maionese', ARRAY[]::text[], 'Temperos e Condimentos', 'Condimentos e Óleos', '1 unidade', 'unidade', null, true, true, null, 184),
  ('Mostarda Amarela', 'mostarda-amarela', 'Mostarda Amarela', ARRAY[]::text[], 'Temperos e Condimentos', 'Condimentos e Óleos', '1 unidade', 'unidade', null, true, true, null, 185),
  ('Mostarda Dijon', 'mostarda-dijon', 'Mostarda Dijon', ARRAY[]::text[], 'Temperos e Condimentos', 'Condimentos e Óleos', '1 unidade', 'unidade', null, true, true, null, 186),
  ('Mostarda Escura', 'mostarda-escura', 'Mostarda Escura', ARRAY[]::text[], 'Temperos e Condimentos', 'Condimentos e Óleos', '1 unidade', 'unidade', null, true, true, null, 187),
  ('Molho Barbecue', 'molho-barbecue', 'Molho Barbecue', ARRAY[]::text[], 'Temperos e Condimentos', 'Condimentos e Óleos', '1 unidade', 'unidade', null, true, true, null, 188),
  ('Molho Inglês', 'molho-ingles', 'Molho Inglês', ARRAY[]::text[], 'Temperos e Condimentos', 'Condimentos e Óleos', '1 unidade', 'unidade', null, true, true, null, 189),
  ('Molho Shoyu', 'molho-shoyu', 'Molho Shoyu', ARRAY[]::text[], 'Temperos e Condimentos', 'Condimentos e Óleos', '1 unidade', 'unidade', null, true, true, null, 190),
  ('Óleo de Coco', 'oleo-de-coco', 'Óleo de Coco', ARRAY[]::text[], 'Temperos e Condimentos', 'Condimentos e Óleos', '1 unidade', 'unidade', null, true, true, null, 191),
  ('Óleo de Soja', 'oleo-de-soja', 'Óleo de Soja', ARRAY[]::text[], 'Temperos e Condimentos', 'Condimentos e Óleos', '1 unidade', 'unidade', null, true, true, null, 192),
  ('Óleo de Girassol', 'oleo-de-girassol', 'Óleo de Girassol', ARRAY[]::text[], 'Temperos e Condimentos', 'Condimentos e Óleos', '1 unidade', 'unidade', null, true, true, null, 193),
  ('Óleo de Algodão', 'oleo-de-algodao', 'Óleo de Algodão', ARRAY[]::text[], 'Temperos e Condimentos', 'Condimentos e Óleos', '1 unidade', 'unidade', null, true, true, null, 194),
  ('Molho de Tomate', 'molho-de-tomate', 'Molho de Tomate', ARRAY[]::text[], 'Despensa', null, '1 unidade', 'unidade', null, true, true, null, 195),
  ('Extrato de Tomate', 'extrato-de-tomate', 'Extrato de Tomate', ARRAY[]::text[], 'Despensa', null, '1 unidade', 'unidade', null, true, true, null, 196),
  ('Tomate Pelado', 'tomate-pelado', 'Tomate Pelado', ARRAY[]::text[], 'Despensa', null, '1 lata', 'lata', null, true, true, null, 197),
  ('Milho em Lata', 'milho-em-lata', 'Milho em Lata', ARRAY[]::text[], 'Despensa', null, '1 lata', 'lata', null, true, true, null, 198),
  ('Ervilha em Lata', 'ervilha-em-lata', 'Ervilha em Lata', ARRAY[]::text[], 'Despensa', null, '1 lata', 'lata', null, true, true, null, 199),
  ('Seleta de Legumes em Lata', 'seleta-de-legumes-em-lata', 'Seleta de Legumes em Lata', ARRAY[]::text[], 'Despensa', null, '1 lata', 'lata', null, true, true, null, 200),
  ('Grão de Bico em Lata', 'grao-de-bico-em-lata', 'Grão de Bico em Lata', ARRAY[]::text[], 'Despensa', null, '1 lata', 'lata', null, true, true, null, 201),
  ('Cogumelos em Conserva', 'cogumelos-em-conserva', 'Cogumelos em Conserva', ARRAY[]::text[], 'Despensa', null, '1 vidro', 'vidro', null, true, true, null, 202),
  ('Palmito em Conserva', 'palmito-em-conserva', 'Palmito em Conserva', ARRAY[]::text[], 'Despensa', null, '1 vidro', 'vidro', null, true, true, null, 203),
  ('Picles em Conserva', 'picles-em-conserva', 'Picles em Conserva', ARRAY[]::text[], 'Despensa', null, '1 vidro', 'vidro', null, true, true, null, 204),
  ('Azeitona Verde em Conserva', 'azeitona-verde-em-conserva', 'Azeitona Verde em Conserva', ARRAY[]::text[], 'Despensa', null, '1 vidro', 'vidro', null, true, true, null, 205),
  ('Azeitona Preta em Conserva', 'azeitona-preta-em-conserva', 'Azeitona Preta em Conserva', ARRAY[]::text[], 'Despensa', null, '1 vidro', 'vidro', null, true, true, null, 206),
  ('Leite de Coco', 'leite-de-coco', 'Leite de Coco', ARRAY[]::text[], 'Despensa', null, '1 unidade', 'unidade', null, true, true, null, 207),
  ('Fermento', 'fermento', 'Fermento', ARRAY[]::text[], 'Despensa', null, '1 unidade', 'unidade', null, true, true, null, 208),
  ('Adoçante Stevia', 'adocante-stevia', 'Adoçante Stevia', ARRAY[]::text[], 'Despensa', null, '1 unidade', 'unidade', null, true, true, null, 209),
  ('Adoçante Sucralose', 'adocante-sucralose', 'Adoçante Sucralose', ARRAY[]::text[], 'Despensa', null, '1 unidade', 'unidade', null, true, true, null, 210),
  ('Gelatina Zero', 'gelatina-zero', 'Gelatina Zero', ARRAY[]::text[], 'Despensa', null, '1 caixa', 'caixa', null, true, true, null, 211),
  ('Água Mineral', 'agua-mineral', 'Água Mineral', ARRAY[]::text[], 'Bebidas', null, '1 garrafa', 'garrafa', null, true, true, null, 212),
  ('Água com Gás', 'agua-com-gas', 'Água com Gás', ARRAY[]::text[], 'Bebidas', null, '1 garrafa', 'garrafa', null, true, true, null, 213),
  ('Água de Coco', 'agua-de-coco', 'Água de Coco', ARRAY[]::text[], 'Bebidas', null, '1 unidade', 'unidade', null, true, true, null, 214),
  ('Bebidas Vegetais', 'bebidas-vegetais', 'Bebidas Vegetais', ARRAY[]::text[], 'Bebidas', null, '1 litro', 'litro', null, true, true, null, 215),
  ('Café em Pó', 'cafe-em-po', 'Café em Pó', ARRAY[]::text[], 'Bebidas', null, '1 pacote', 'pacote', null, true, true, null, 216),
  ('Café em Grãos', 'cafe-em-graos', 'Café em Grãos', ARRAY[]::text[], 'Bebidas', null, '1 pacote', 'pacote', null, true, true, null, 217),
  ('Cápsulas de Café', 'capsulas-de-cafe', 'Cápsulas de Café', ARRAY[]::text[], 'Bebidas', null, '1 caixa', 'caixa', null, true, true, null, 218),
  ('Chá', 'cha', 'Chá', ARRAY[]::text[], 'Bebidas', null, '1 caixa', 'caixa', null, true, true, null, 219),
  ('Chá Gelado', 'cha-gelado', 'Chá Gelado', ARRAY[]::text[], 'Bebidas', null, '1 unidade', 'unidade', null, true, true, null, 220),
  ('Energéticos', 'energeticos', 'Energéticos', ARRAY[]::text[], 'Bebidas', null, '1 unidade', 'unidade', null, true, true, null, 221),
  ('Refrigerante', 'refrigerante', 'Refrigerante', ARRAY[]::text[], 'Bebidas', null, '1 unidade', 'unidade', null, true, true, null, 222),
  ('Refresco em Pó Clight Zero', 'refresco-em-po-clight-zero', 'Refresco em Pó Clight Zero', ARRAY[]::text[], 'Bebidas', null, '1 pacote', 'pacote', null, true, true, null, 223),
  ('Refresco em Pó MID Zero', 'refresco-em-po-mid-zero', 'Refresco em Pó MID Zero', ARRAY[]::text[], 'Bebidas', null, '1 pacote', 'pacote', null, true, true, null, 224),
  ('Suco de Uva Integral', 'suco-de-uva-integral', 'Suco de Uva Integral', ARRAY[]::text[], 'Bebidas', null, '1 unidade', 'unidade', null, true, true, null, 225),
  ('Suco de Maçã Integral', 'suco-de-maca-integral', 'Suco de Maçã Integral', ARRAY[]::text[], 'Bebidas', null, '1 unidade', 'unidade', null, true, true, null, 226),
  ('Suco de Laranja Integral', 'suco-de-laranja-integral', 'Suco de Laranja Integral', ARRAY[]::text[], 'Bebidas', null, '1 unidade', 'unidade', null, true, true, null, 227)
on conflict (slug) do update set
  name = excluded.name,
  display_name = excluded.display_name,
  aliases = excluded.aliases,
  shopping_category = excluded.shopping_category,
  shopping_subcategory = excluded.shopping_subcategory,
  default_quantity_text = excluded.default_quantity_text,
  default_unit = excluded.default_unit,
  notes = excluded.notes,
  is_active = excluded.is_active,
  is_food = excluded.is_food,
  ingredient_id = excluded.ingredient_id,
  sort_order = excluded.sort_order,
  updated_at = now();

-- These older generic entries are now represented by specific buyable catalog items
-- such as "Vinagre de Maçã", "Café em Pó" and "Suco de Uva Integral".
update public.shopping_catalog_items
set
  is_active = false,
  updated_at = now()
where slug in (
  'aveia',
  'castanhas',
  'cafe',
  'cebola',
  'chia',
  'curry',
  'feijao',
  'frutas-congeladas',
  'iogurte-natural',
  'linhaca',
  'legumes-congelados',
  'milho',
  'ervilha',
  'azeitona',
  'leite',
  'mel',
  'mostarda',
  'oleo',
  'paprica',
  'polpa-de-fruta',
  'sobrecoxa',
  'suco-zero',
  'uva',
  'vinagre'
);
