-- Generated from docs\catalogo_compras_rascunho.md.
-- Run after migrations that create public.shopping_catalog_items.

insert into public.shopping_catalog_items (
  name,
  slug,
  display_name,
  aliases,
  shopping_category,
  shopping_subcategory,
  default_quantity_text,
  default_unit,
  notes,
  is_active,
  is_food,
  ingredient_id,
  sort_order
)
values
  ('Peito de Frango', 'peito-de-frango', 'Peito de Frango', ARRAY[]::text[], 'Proteínas', 'Aves', '2kg', 'kg', null, true, true, null, 1),
  ('Sobrecoxa', 'sobrecoxa', 'Sobrecoxa', ARRAY[]::text[], 'Proteínas', 'Aves', '1kg', 'kg', null, true, true, null, 2),
  ('Coxa de Frango', 'coxa-de-frango', 'Coxa de Frango', ARRAY[]::text[], 'Proteínas', 'Aves', '1kg', 'kg', null, true, true, null, 3),
  ('Frango Moído', 'frango-moido', 'Frango Moído', ARRAY[]::text[], 'Proteínas', 'Aves', '1kg', 'kg', null, true, true, null, 4),
  ('Filé de Frango', 'file-de-frango', 'Filé de Frango', ARRAY[]::text[], 'Proteínas', 'Aves', '1kg', 'kg', null, true, true, null, 5),
  ('Patinho', 'patinho', 'Patinho', ARRAY[]::text[], 'Proteínas', 'Bovinos', '1kg', 'kg', null, true, true, null, 6),
  ('Carne Moída', 'carne-moida', 'Carne Moída', ARRAY[]::text[], 'Proteínas', 'Bovinos', '1kg', 'kg', null, true, true, null, 7),
  ('Carne de Panela', 'carne-de-panela', 'Carne de Panela', ARRAY[]::text[], 'Proteínas', 'Bovinos', '1kg', 'kg', null, true, true, null, 8),
  ('Acém', 'acem', 'Acém', ARRAY[]::text[], 'Proteínas', 'Bovinos', '1kg', 'kg', null, true, true, null, 9),
  ('Paleta', 'paleta', 'Paleta', ARRAY[]::text[], 'Proteínas', 'Bovinos', '1kg', 'kg', null, true, true, null, 10),
  ('Lombo Suíno', 'lombo-suino', 'Lombo Suíno', ARRAY[]::text[], 'Proteínas', 'Suínos', '1kg', 'kg', null, true, true, null, 11),
  ('Pernil Suíno', 'pernil-suino', 'Pernil Suíno', ARRAY[]::text[], 'Proteínas', 'Suínos', '1kg', 'kg', null, true, true, null, 12),
  ('Costelinha Suína', 'costelinha-suina', 'Costelinha Suína', ARRAY[]::text[], 'Proteínas', 'Suínos', '1kg', 'kg', null, true, true, null, 13),
  ('Filé de Tilápia', 'file-de-tilapia', 'Filé de Tilápia', ARRAY[]::text[], 'Proteínas', 'Peixes', '1kg', 'kg', null, true, true, null, 14),
  ('Salmão', 'salmao', 'Salmão', ARRAY[]::text[], 'Proteínas', 'Peixes', '500g', 'g', null, true, true, null, 15),
  ('Camarão', 'camarao', 'Camarão', ARRAY[]::text[], 'Proteínas', 'Peixes', '500g', 'g', null, true, true, null, 16),
  ('Ovos', 'ovos', 'Ovos', ARRAY[]::text[], 'Proteínas', 'Proteínas em Conserva e Ovos', '30und', 'und', null, true, true, null, 17),
  ('Atum em lata', 'atum-em-lata', 'Atum em lata', ARRAY[]::text[], 'Proteínas', 'Proteínas em Conserva e Ovos', '1 lata', 'lata', null, true, true, null, 18),
  ('Sardinha em lata', 'sardinha-em-lata', 'Sardinha em lata', ARRAY[]::text[], 'Proteínas', 'Proteínas em Conserva e Ovos', '1 lata', 'lata', null, true, true, null, 19),
  ('Presunto', 'presunto', 'Presunto', ARRAY[]::text[], 'Proteínas', 'Frios', '200g', 'g', null, true, true, null, 20),
  ('Peito de Peru', 'peito-de-peru', 'Peito de Peru', ARRAY[]::text[], 'Proteínas', 'Frios', '200g', 'g', null, true, true, null, 21),
  ('Muçarela fatiada', 'mucarela-fatiada', 'Muçarela fatiada', ARRAY[]::text[], 'Proteínas', 'Frios', '200g', 'g', null, true, true, null, 22),
  ('Arroz', 'arroz', 'Arroz', ARRAY[]::text[], 'Carboidratos', 'Carboidratos de Base', null, null, null, true, true, null, 23),
  ('Arroz Integral', 'arroz-integral', 'Arroz Integral', ARRAY[]::text[], 'Carboidratos', 'Carboidratos de Base', null, null, null, true, true, null, 24),
  ('Feijão', 'feijao', 'Feijão', ARRAY[]::text[], 'Carboidratos', 'Carboidratos de Base', null, null, null, true, true, null, 25),
  ('Macarrão', 'macarrao', 'Macarrão', ARRAY[]::text[], 'Carboidratos', 'Carboidratos de Base', null, null, null, true, true, null, 26),
  ('Batata Inglesa', 'batata-inglesa', 'Batata Inglesa', ARRAY[]::text[], 'Carboidratos', 'Carboidratos de Base', '1kg', 'kg', null, true, true, null, 27),
  ('Batata Doce', 'batata-doce', 'Batata Doce', ARRAY[]::text[], 'Carboidratos', 'Carboidratos de Base', '1kg', 'kg', null, true, true, null, 28),
  ('Mandioca', 'mandioca', 'Mandioca', ARRAY['Macaxeira', 'Aipim']::text[], 'Carboidratos', 'Carboidratos de Base', '1kg', 'kg', null, true, true, null, 29),
  ('Cuscuz', 'cuscuz', 'Cuscuz', ARRAY[]::text[], 'Carboidratos', 'Carboidratos de Base', '1 pacote', 'pacote', null, true, true, null, 30),
  ('Tapioca', 'tapioca', 'Tapioca', ARRAY[]::text[], 'Carboidratos', 'Carboidratos Práticos', '1 pacote', 'pacote', null, true, true, null, 31),
  ('Pão Francês', 'pao-frances', 'Pão Francês', ARRAY[]::text[], 'Carboidratos', 'Carboidratos Práticos', '12 unidades', 'unidades', null, true, true, null, 32),
  ('Pão Integral', 'pao-integral', 'Pão Integral', ARRAY[]::text[], 'Carboidratos', 'Carboidratos Práticos', '1 pacote', 'pacote', null, true, true, null, 33),
  ('Aveia', 'aveia', 'Aveia', ARRAY['Aveia em Flocos', 'Farinha de Aveia', 'Farelo de Aveia']::text[], 'Carboidratos', 'Carboidratos Práticos', '1 pacote', 'pacote', null, true, true, null, 34),
  ('Granola', 'granola', 'Granola', ARRAY[]::text[], 'Carboidratos', 'Carboidratos Práticos', '1 pacote', 'pacote', null, true, true, null, 35),
  ('Farinha de Tapioca', 'farinha-de-tapioca', 'Farinha de Tapioca', ARRAY[]::text[], 'Carboidratos', 'Carboidratos Práticos', '1 pacote', 'pacote', null, true, true, null, 36),
  ('Mel', 'mel', 'Mel', ARRAY[]::text[], 'Carboidratos', 'Doces e Açúcares', '1 unidade', 'unidade', null, true, true, null, 37),
  ('Açúcar', 'acucar', 'Açúcar', ARRAY[]::text[], 'Carboidratos', 'Doces e Açúcares', '1kg', 'kg', null, true, true, null, 38),
  ('Chocolate 70%', 'chocolate-70', 'Chocolate 70%', ARRAY[]::text[], 'Carboidratos', 'Doces e Açúcares', '1 unidade', 'unidade', null, true, true, null, 39),
  ('Alface', 'alface', 'Alface', ARRAY[]::text[], 'Vegetais', 'Verduras', '1 unidade', 'unidade', null, true, true, null, 40),
  ('Rúcula', 'rucula', 'Rúcula', ARRAY[]::text[], 'Vegetais', 'Verduras', '1 maço', 'maço', null, true, true, null, 41),
  ('Couve', 'couve', 'Couve', ARRAY[]::text[], 'Vegetais', 'Verduras', '1 maço', 'maço', null, true, true, null, 42),
  ('Espinafre', 'espinafre', 'Espinafre', ARRAY[]::text[], 'Vegetais', 'Verduras', '1 maço', 'maço', null, true, true, null, 43),
  ('Tomate', 'tomate', 'Tomate', ARRAY[]::text[], 'Vegetais', 'Legumes', '1kg', 'kg', null, true, true, null, 44),
  ('Cebola', 'cebola', 'Cebola', ARRAY[]::text[], 'Vegetais', 'Legumes', '1kg', 'kg', null, true, true, null, 45),
  ('Alho', 'alho', 'Alho', ARRAY[]::text[], 'Vegetais', 'Legumes', '1 cabeça', 'cabeça', null, true, true, null, 46),
  ('Cenoura', 'cenoura', 'Cenoura', ARRAY[]::text[], 'Vegetais', 'Legumes', '1kg', 'kg', null, true, true, null, 47),
  ('Brócolis', 'brocolis', 'Brócolis', ARRAY[]::text[], 'Vegetais', 'Legumes', '1 unidade', 'unidade', null, true, true, null, 48),
  ('Abóbora', 'abobora', 'Abóbora', ARRAY[]::text[], 'Vegetais', 'Legumes', '1kg', 'kg', null, true, true, null, 49),
  ('Pepino', 'pepino', 'Pepino', ARRAY[]::text[], 'Vegetais', 'Legumes', '2 unidades', 'unidades', null, true, true, null, 50),
  ('Beterraba', 'beterraba', 'Beterraba', ARRAY[]::text[], 'Vegetais', 'Legumes', '1kg', 'kg', null, true, true, null, 51),
  ('Repolho', 'repolho', 'Repolho', ARRAY[]::text[], 'Vegetais', 'Legumes', '1 unidade', 'unidade', null, true, true, null, 52),
  ('Abobrinha', 'abobrinha', 'Abobrinha', ARRAY[]::text[], 'Vegetais', 'Legumes', '1kg', 'kg', null, true, true, null, 53),
  ('Chuchu', 'chuchu', 'Chuchu', ARRAY[]::text[], 'Vegetais', 'Legumes', '1kg', 'kg', null, true, true, null, 54),
  ('Castanhas', 'castanhas', 'Castanhas', ARRAY[]::text[], 'Vegetais', 'Oleaginosas, Sementes e Fibras', '500g', 'g', null, true, true, null, 55),
  ('Chia', 'chia', 'Chia', ARRAY[]::text[], 'Vegetais', 'Oleaginosas, Sementes e Fibras', '1 pacote', 'pacote', null, true, true, null, 56),
  ('Linhaça', 'linhaca', 'Linhaça', ARRAY[]::text[], 'Vegetais', 'Oleaginosas, Sementes e Fibras', '1 pacote', 'pacote', null, true, true, null, 57),
  ('Banana', 'banana', 'Banana', ARRAY[]::text[], 'Frutas', 'Frutas de Casa', '12 unidades', 'unidades', null, true, true, null, 58),
  ('Maçã', 'maca', 'Maçã', ARRAY[]::text[], 'Frutas', 'Frutas de Casa', '1kg', 'kg', null, true, true, null, 59),
  ('Mamão', 'mamao', 'Mamão', ARRAY[]::text[], 'Frutas', 'Frutas de Casa', '1 unidade', 'unidade', null, true, true, null, 60),
  ('Laranja', 'laranja', 'Laranja', ARRAY[]::text[], 'Frutas', 'Frutas de Casa', '1kg', 'kg', null, true, true, null, 61),
  ('Manga', 'manga', 'Manga', ARRAY[]::text[], 'Frutas', 'Frutas de Casa', '1kg', 'kg', null, true, true, null, 62),
  ('Melancia', 'melancia', 'Melancia', ARRAY[]::text[], 'Frutas', 'Frutas de Casa', '1 unidade', 'unidade', null, true, true, null, 63),
  ('Goiaba', 'goiaba', 'Goiaba', ARRAY[]::text[], 'Frutas', 'Frutas de Rua', '1kg', 'kg', null, true, true, null, 64),
  ('Abacaxi', 'abacaxi', 'Abacaxi', ARRAY[]::text[], 'Frutas', 'Frutas de Rua', '1 unidade', 'unidade', null, true, true, null, 65),
  ('Uva', 'uva', 'Uva', ARRAY[]::text[], 'Frutas', 'Frutas de Rua', '1 bandeja', 'bandeja', null, true, true, null, 66),
  ('Morango', 'morango', 'Morango', ARRAY[]::text[], 'Frutas', 'Frutas de Rua', '1 bandeja', 'bandeja', null, true, true, null, 67),
  ('Pera', 'pera', 'Pera', ARRAY[]::text[], 'Frutas', 'Frutas de Rua', '1kg', 'kg', null, true, true, null, 68),
  ('Kiwi', 'kiwi', 'Kiwi', ARRAY[]::text[], 'Frutas', 'Frutas de Rua', '1 bandeja', 'bandeja', null, true, true, null, 69),
  ('Iogurte Natural', 'iogurte-natural', 'Iogurte Natural', ARRAY[]::text[], 'Laticínios', null, '1 unidade', 'unidade', null, true, true, null, 70),
  ('Leite', 'leite', 'Leite', ARRAY[]::text[], 'Laticínios', null, '1 litro', 'litro', null, true, true, null, 71),
  ('Queijo Cottage', 'queijo-cottage', 'Queijo Cottage', ARRAY[]::text[], 'Laticínios', null, '1 pote', 'pote', null, true, true, null, 72),
  ('Muçarela', 'mucarela', 'Muçarela', ARRAY[]::text[], 'Laticínios', null, '1 pacote', 'pacote', null, true, true, null, 73),
  ('Parmesão', 'parmesao', 'Parmesão', ARRAY[]::text[], 'Laticínios', null, '1 pacote', 'pacote', null, true, true, null, 74),
  ('Ricota', 'ricota', 'Ricota', ARRAY[]::text[], 'Laticínios', null, '1 unidade', 'unidade', null, true, true, null, 75),
  ('Cream Cheese', 'cream-cheese', 'Cream Cheese', ARRAY[]::text[], 'Laticínios', null, '1 pote', 'pote', null, true, true, null, 76),
  ('Requeijão', 'requeijao', 'Requeijão', ARRAY[]::text[], 'Laticínios', null, '1 unidade', 'unidade', null, true, true, null, 77),
  ('Legumes Congelados', 'legumes-congelados', 'Legumes Congelados', ARRAY[]::text[], 'Congelados', null, '1 pacote', 'pacote', null, true, true, null, 78),
  ('Brócolis Congelado', 'brocolis-congelado', 'Brócolis Congelado', ARRAY[]::text[], 'Congelados', null, '1 pacote', 'pacote', null, true, true, null, 79),
  ('Frutas Congeladas', 'frutas-congeladas', 'Frutas Congeladas', ARRAY[]::text[], 'Congelados', null, '1 pacote', 'pacote', null, true, true, null, 80),
  ('Polpa de Fruta', 'polpa-de-fruta', 'Polpa de Fruta', ARRAY[]::text[], 'Congelados', null, '1 pacote', 'pacote', null, true, true, null, 81),
  ('Sal', 'sal', 'Sal', ARRAY[]::text[], 'Temperos e Condimentos', 'Temperos Secos', '1 pacote', 'pacote', null, true, true, null, 82),
  ('Pimenta', 'pimenta', 'Pimenta', ARRAY[]::text[], 'Temperos e Condimentos', 'Temperos Secos', '1 unidade', 'unidade', null, true, true, null, 83),
  ('Páprica', 'paprica', 'Páprica', ARRAY[]::text[], 'Temperos e Condimentos', 'Temperos Secos', '1 unidade', 'unidade', null, true, true, null, 84),
  ('Orégano', 'oregano', 'Orégano', ARRAY[]::text[], 'Temperos e Condimentos', 'Temperos Secos', '1 unidade', 'unidade', null, true, true, null, 85),
  ('Chimichurri', 'chimichurri', 'Chimichurri', ARRAY[]::text[], 'Temperos e Condimentos', 'Temperos Secos', '1 unidade', 'unidade', null, true, true, null, 86),
  ('Açafrão', 'acafrao', 'Açafrão', ARRAY[]::text[], 'Temperos e Condimentos', 'Temperos Secos', '1 unidade', 'unidade', null, true, true, null, 87),
  ('Curry', 'curry', 'Curry', ARRAY[]::text[], 'Temperos e Condimentos', 'Temperos Secos', '1 unidade', 'unidade', null, true, true, null, 88),
  ('Cominho', 'cominho', 'Cominho', ARRAY[]::text[], 'Temperos e Condimentos', 'Temperos Secos', '1 unidade', 'unidade', null, true, true, null, 89),
  ('Alho em Pó', 'alho-em-po', 'Alho em Pó', ARRAY[]::text[], 'Temperos e Condimentos', 'Temperos Secos', '1 unidade', 'unidade', null, true, true, null, 90),
  ('Cebola em Pó', 'cebola-em-po', 'Cebola em Pó', ARRAY[]::text[], 'Temperos e Condimentos', 'Temperos Secos', '1 unidade', 'unidade', null, true, true, null, 91),
  ('Louro', 'louro', 'Louro', ARRAY[]::text[], 'Temperos e Condimentos', 'Ervas Desidratadas', '1 pacote', 'pacote', null, true, true, null, 92),
  ('Manjericão', 'manjericao', 'Manjericão', ARRAY[]::text[], 'Temperos e Condimentos', 'Ervas Desidratadas', '1 unidade', 'unidade', null, true, true, null, 93),
  ('Alecrim', 'alecrim', 'Alecrim', ARRAY[]::text[], 'Temperos e Condimentos', 'Ervas Desidratadas', '1 unidade', 'unidade', null, true, true, null, 94),
  ('Molho de Tomate', 'molho-de-tomate', 'Molho de Tomate', ARRAY[]::text[], 'Temperos e Condimentos', 'Condimentos e Óleos', '1 unidade', 'unidade', null, true, true, null, 95),
  ('Ketchup', 'ketchup', 'Ketchup', ARRAY[]::text[], 'Temperos e Condimentos', 'Condimentos e Óleos', '1 unidade', 'unidade', null, true, true, null, 96),
  ('Mostarda', 'mostarda', 'Mostarda', ARRAY['Mostarda Amarela', 'Mostarda Dijon', 'Mostarda Escura']::text[], 'Temperos e Condimentos', 'Condimentos e Óleos', '1 unidade', 'unidade', null, true, true, null, 97),
  ('Azeite', 'azeite', 'Azeite', ARRAY[]::text[], 'Temperos e Condimentos', 'Condimentos e Óleos', '1 vidro', 'vidro', null, true, true, null, 98),
  ('Óleo', 'oleo', 'Óleo', ARRAY[]::text[], 'Temperos e Condimentos', 'Condimentos e Óleos', '1 unidade', 'unidade', null, true, true, null, 99),
  ('Vinagre', 'vinagre', 'Vinagre', ARRAY['Vinagre de maçã', 'Vinagre de álcool', 'Vinagre de arroz', 'Vinagre Balsâmico']::text[], 'Temperos e Condimentos', 'Condimentos e Óleos', '1 unidade', 'unidade', null, true, true, null, 100),
  ('Molho Shoyu', 'molho-shoyu', 'Molho Shoyu', ARRAY[]::text[], 'Temperos e Condimentos', 'Condimentos e Óleos', '1 unidade', 'unidade', null, true, true, null, 101),
  ('Milho', 'milho', 'Milho', ARRAY[]::text[], 'Despensa', null, '1 lata', 'lata', null, true, true, null, 102),
  ('Ervilha', 'ervilha', 'Ervilha', ARRAY[]::text[], 'Despensa', null, '1 lata', 'lata', null, true, true, null, 103),
  ('Palmito', 'palmito', 'Palmito', ARRAY[]::text[], 'Despensa', null, '1 vidro', 'vidro', null, true, true, null, 104),
  ('Azeitona', 'azeitona', 'Azeitona', ARRAY[]::text[], 'Despensa', null, '1 vidro', 'vidro', null, true, true, null, 105),
  ('Leite de Coco', 'leite-de-coco', 'Leite de Coco', ARRAY[]::text[], 'Despensa', null, '1 unidade', 'unidade', null, true, true, null, 106),
  ('Pasta de Amendoim', 'pasta-de-amendoim', 'Pasta de Amendoim', ARRAY[]::text[], 'Despensa', null, '1 pote', 'pote', null, true, true, null, 107),
  ('Creme de Leite', 'creme-de-leite', 'Creme de Leite', ARRAY[]::text[], 'Despensa', null, '1 unidade', 'unidade', null, true, true, null, 108),
  ('Água Mineral', 'agua-mineral', 'Água Mineral', ARRAY[]::text[], 'Bebidas', null, '1 garrafa', 'garrafa', null, true, true, null, 109),
  ('Água com Gás', 'agua-com-gas', 'Água com Gás', ARRAY[]::text[], 'Bebidas', null, '1 garrafa', 'garrafa', null, true, true, null, 110),
  ('Isotônico', 'isotonico', 'Isotônico', ARRAY[]::text[], 'Bebidas', null, '1 unidade', 'unidade', null, true, true, null, 111),
  ('Suco Zero', 'suco-zero', 'Suco Zero', ARRAY[]::text[], 'Bebidas', null, '1 unidade', 'unidade', null, true, true, null, 112),
  ('Café', 'cafe', 'Café', ARRAY['Café em Pó', 'Café em Grãos', 'Cápsulas de Café']::text[], 'Bebidas', null, '1 pacote', 'pacote', null, true, true, null, 113),
  ('Chá', 'cha', 'Chá', ARRAY[]::text[], 'Bebidas', null, '1 caixa', 'caixa', null, true, true, null, 114),
  ('Água de Coco', 'agua-de-coco', 'Água de Coco', ARRAY[]::text[], 'Bebidas', null, '1 unidade', 'unidade', null, true, true, null, 115),
  ('Saco Zip', 'saco-zip', 'Saco Zip', ARRAY[]::text[], 'Utilidades', null, '1 pacote', 'pacote', null, true, false, null, 116),
  ('Papel Alumínio', 'papel-aluminio', 'Papel Alumínio', ARRAY[]::text[], 'Utilidades', null, '1 rolo', 'rolo', null, true, false, null, 117),
  ('Papel Toalha', 'papel-toalha', 'Papel Toalha', ARRAY[]::text[], 'Utilidades', null, '1 pacote', 'pacote', null, true, false, null, 118),
  ('Marmita Descartável', 'marmita-descartavel', 'Marmita Descartável', ARRAY[]::text[], 'Utilidades', null, '1 pacote', 'pacote', null, true, false, null, 119),
  ('Guardanapo', 'guardanapo', 'Guardanapo', ARRAY[]::text[], 'Utilidades', null, '1 pacote', 'pacote', null, true, false, null, 120),
  ('Filme Plástico', 'filme-plastico', 'Filme Plástico', ARRAY[]::text[], 'Utilidades', null, '1 rolo', 'rolo', null, true, false, null, 121),
  ('Etiquetas', 'etiquetas', 'Etiquetas', ARRAY[]::text[], 'Utilidades', null, '1 pacote', 'pacote', null, true, false, null, 122),
  ('Sacos para Congelamento', 'sacos-para-congelamento', 'Sacos para Congelamento', ARRAY[]::text[], 'Utilidades', null, '1 pacote', 'pacote', null, true, false, null, 123)
on conflict (slug) do update set
  name = excluded.name,
  display_name = excluded.display_name,
  aliases = excluded.aliases,
  shopping_category = excluded.shopping_category,
  shopping_subcategory = excluded.shopping_subcategory,
  default_quantity_text = excluded.default_quantity_text,
  default_unit = excluded.default_unit,
  notes = excluded.notes,
  is_active = excluded.is_active,
  is_food = excluded.is_food,
  ingredient_id = excluded.ingredient_id,
  sort_order = excluded.sort_order,
  updated_at = now();
